#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 rc4l

# [rc4l] Stand up a ForkUnderA server on this box. Nothing to edit, here or afterwards.
#
#   curl -fsSL https://raw.githubusercontent.com/rc4l/forkundera-game-server/main/host.sh | sudo bash -s duel40
#
# Re-running upgrades in place and keeps the WAD store. Adding a second server is the same command
# with a different --port.
#
# WHAT THIS DELIBERATELY IS NOT. It is a bootstrapper, not a configuration tool. Everything about what
# a server PLAYS lives in its catalogue entry, which is data the image already carries or that you drop
# in a volume; everything about how it RUNS is a flag below. The moment this script starts asking
# questions it has become the web panel nobody wanted.
set -euo pipefail

IMAGE="${FUA_IMAGE:-ghcr.io/rc4l/forkundera-game-server:latest}"
ROOT="${FUA_ROOT:-/opt/forkundera-game-server}"

# [rc4l] ONE volume for every server on the box, and this is the whole reason ten servers cost what
# one costs on disk. The image stores downloads content-addressed (by-md5/<digest>/<name>), so a 200 MB
# mod fetched for the first server is already present for the other nine, and nothing can clobber
# anything else. A per-instance volume would re-download the same file for every server that wants it.
VOLUME="${FUA_VOLUME:-forkundera-wads}"

ENTRY=""
VARIANT=""
PORT=10666
NAME=""
PLAYERS=8
RCON=""
PASSWORD=""
REGISTRY=""
ANNOUNCE=1

usage() {
	cat <<'USAGE'
Usage: host.sh <entry> [options]

  <entry>              catalogue id to host, e.g. duel40

  --variant ID         which way to play the entry (its default if omitted)
  --port N             UDP+TCP port (default 10666). A second server needs a different one.
  --name "..."         server name shown in the browser
  --players N          player limit (default 8)
  --rcon SECRET        remote admin password
  --password SECRET    password required to join
  --registry HOST      announce to a different server registry
  --private            do not announce at all
  --image REF          override the container image

Run it again with a different --port to add another server. Run it again with the SAME port to
upgrade that one in place.
USAGE
}

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==>\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m==> %s\033[0m\n' "$*" >&2; exit 1; }

[ $# -gt 0 ] || { usage; exit 2; }
case "$1" in -h|--help) usage; exit 0 ;; esac
ENTRY="$1"; shift

while [ $# -gt 0 ]; do
	case "$1" in
		--variant)  VARIANT="${2:?--variant needs a value}"; shift 2 ;;
		--port)     PORT="${2:?--port needs a value}"; shift 2 ;;
		--name)     NAME="${2:?--name needs a value}"; shift 2 ;;
		--players)  PLAYERS="${2:?--players needs a value}"; shift 2 ;;
		--rcon)     RCON="${2:?--rcon needs a value}"; shift 2 ;;
		--password) PASSWORD="${2:?--password needs a value}"; shift 2 ;;
		--registry) REGISTRY="${2:?--registry needs a value}"; shift 2 ;;
		--image)    IMAGE="${2:?--image needs a value}"; shift 2 ;;
		--private)  ANNOUNCE=0; shift ;;
		-h|--help)  usage; exit 0 ;;
		*)          die "unknown option: $1" ;;
	esac
done

case "${PORT}" in ''|*[!0-9]*) die "--port must be a number" ;; esac
[ "${PORT}" -ge 1024 ] && [ "${PORT}" -le 65535 ] || die "--port must be between 1024 and 65535"

[ "$(id -u)" -eq 0 ] || die "run this as root (it writes ${ROOT}, opens a firewall port and talks to docker)"

INSTANCE="${ENTRY}${VARIANT:+-${VARIANT}}-${PORT}"
DIR="${ROOT}/instances/${INSTANCE}"

#---------------------------------------------------------------------------------------------------
# Docker
#---------------------------------------------------------------------------------------------------

if ! command -v docker >/dev/null 2>&1; then
	log "installing docker"
	curl -fsSL https://get.docker.com | sh
fi

# [rc4l] `docker compose` (plugin) on anything current, `docker-compose` on older boxes. Checked rather
# than assumed, because the failure is otherwise a confusing "unknown command" halfway through setup.
if docker compose version >/dev/null 2>&1; then
	COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
	COMPOSE="docker-compose"
else
	die "no docker compose available; install the compose plugin"
fi

docker volume inspect "${VOLUME}" >/dev/null 2>&1 || {
	log "creating shared WAD volume ${VOLUME}"
	docker volume create "${VOLUME}" >/dev/null
}

#---------------------------------------------------------------------------------------------------
# The compose file
#---------------------------------------------------------------------------------------------------

mkdir -p "${DIR}"

{
	echo "# Generated by host.sh. Re-running the script rewrites this file."
	echo "# Edit it if you like -- but the script is the supported way, and it will overwrite you."
	echo "services:"
	echo "  server:"
	echo "    image: ${IMAGE}"
	echo "    container_name: fua-${INSTANCE}"
	# [rc4l] HOST NETWORKING, and it is not a preference.
	#
	# The registry lists a server at the source address AND PORT of its own announce packet
	# (server-registry/main.cpp: newServer.Address = AddressFrom). Behind a bridge network the announce
	# leaves masqueraded, so the registry publishes an address nothing is listening on -- intermittently,
	# because NAT usually but not always preserves the port, which is worse than never working.
	#
	# Inbound matters just as much: sv_maxclientsperip defaults to 2 and both server bans and the
	# registry's pushed ban list match on client address, so a bridge that rewrites every client to the
	# gateway caps the server at two players and breaks every ban at once.
	echo "    network_mode: host"
	echo "    restart: unless-stopped"
	echo "    stop_grace_period: 30s"
	echo "    volumes:"
	echo "      - ${VOLUME}:/data"
	echo "    environment:"
	echo "      FUA_ENTRY: \"${ENTRY}\""
	echo "      FUA_PORT: \"${PORT}\""
	echo "      FUA_PLAYERS: \"${PLAYERS}\""
	echo "      FUA_ANNOUNCE: \"${ANNOUNCE}\""
	[ -n "${VARIANT}" ]  && echo "      FUA_VARIANT: \"${VARIANT}\""
	[ -n "${NAME}" ]     && echo "      FUA_NAME: \"${NAME}\""
	[ -n "${RCON}" ]     && echo "      FUA_RCON: \"${RCON}\""
	[ -n "${PASSWORD}" ] && echo "      FUA_PASSWORD: \"${PASSWORD}\""
	[ -n "${REGISTRY}" ] && echo "      FUA_REGISTRY: \"${REGISTRY}\""
	echo "    logging:"
	echo "      driver: json-file"
	echo "      options: { max-size: \"10m\", max-file: \"3\" }"
	echo "volumes:"
	echo "  ${VOLUME}:"
	echo "    external: true"
} > "${DIR}/docker-compose.yml"

# [rc4l] The generated file can carry an rcon or join password, so it is not world-readable.
chmod 600 "${DIR}/docker-compose.yml"

#---------------------------------------------------------------------------------------------------
# Firewall
#
# [rc4l] BOTH protocols, same number. UDP carries the game; TCP is the server handing joiners the WADs
# it runs. Opening only UDP is the failure that looks like success: the server works perfectly and
# every download from it fails.
#
# Only the HOST firewall is touched. A router in front of this box is not something a script inside it
# can reach or should pretend to, and the registry answers the reachability question for real further
# down by trying to reach us from outside.
#---------------------------------------------------------------------------------------------------

if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "^Status: active"; then
	log "opening ${PORT}/udp and ${PORT}/tcp (ufw)"
	ufw allow "${PORT}/udp" >/dev/null || warn "could not add the ufw udp rule"
	ufw allow "${PORT}/tcp" >/dev/null || warn "could not add the ufw tcp rule"
elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
	log "opening ${PORT}/udp and ${PORT}/tcp (firewalld)"
	firewall-cmd --permanent --add-port="${PORT}/udp" >/dev/null || warn "could not add the firewalld udp rule"
	firewall-cmd --permanent --add-port="${PORT}/tcp" >/dev/null || warn "could not add the firewalld tcp rule"
	firewall-cmd --reload >/dev/null || true
else
	warn "no active ufw or firewalld found; make sure ${PORT}/udp AND ${PORT}/tcp reach this box"
fi

#---------------------------------------------------------------------------------------------------
# Go
#---------------------------------------------------------------------------------------------------

log "pulling ${IMAGE}"
$COMPOSE -f "${DIR}/docker-compose.yml" pull -q 2>/dev/null || $COMPOSE -f "${DIR}/docker-compose.yml" pull

log "starting ${INSTANCE}"
# [rc4l] --force-recreate, always. Compose compares the COMPOSE FILE and leaves the container alone
# when it has not changed, which is the wrong question here: almost nothing this script exists to
# change lives in that file.
#
# The catalogue lives in the image, the WADs live in the shared volume, and the entry is re-resolved
# from both every time the entrypoint runs. So dropping doom2.wad into /data/wads and re-running with
# the same arguments did nothing at all -- four servers kept their substituted Freedoom, and the logs
# went on saying "substituted" while it looked like a successful deploy. It took a docker restart to
# apply, which is not something an operator should have to know.
#
# Recreating costs a few seconds of downtime on the one server named on the command line. Running this
# script is already an explicit act, and "I ran the deploy command and nothing happened" is the worse
# failure by a distance.
$COMPOSE -f "${DIR}/docker-compose.yml" up -d --force-recreate

#---------------------------------------------------------------------------------------------------
# Say what happened
#
# [rc4l] Reachability is REPORTED, never predicted. A machine cannot tell from the inside whether its
# port is forwarded -- checking your own port proves only that you can talk to yourself. The registry
# runs the one test that counts, by sending an unsolicited packet from outside and refusing to list a
# server that does not answer, so waiting a few seconds and reading the log is a real answer where a
# local probe would be theatre.
#---------------------------------------------------------------------------------------------------

log "waiting for the server to come up"
ready=0
for _ in $(seq 1 30); do
	if docker logs "fua-${INSTANCE}" 2>&1 | grep -q "UDP Initialized"; then ready=1; break; fi
	if [ "$(docker inspect -f '{{.State.Running}}' "fua-${INSTANCE}" 2>/dev/null)" != "true" ]; then break; fi
	sleep 2
done

echo
if [ "$ready" -ne 1 ]; then
	warn "the server did not report a bound socket. Its log:"
	docker logs --tail 40 "fua-${INSTANCE}" 2>&1 || true
	die "start failed"
fi

ip="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo "<this box>")"

log "up: ${ip}:${PORT}"
docker logs "fua-${INSTANCE}" 2>&1 | grep -E "^\*\*\*|WAD serving enabled" | tail -3 || true

cat <<EOF

  instance   ${INSTANCE}
  compose    ${DIR}/docker-compose.yml
  logs       docker logs -f fua-${INSTANCE}
  stop       ${COMPOSE} -f ${DIR}/docker-compose.yml down
  add one    host.sh <entry> --port $((PORT + 1))

EOF

if [ "${ANNOUNCE}" = "1" ]; then
	log "announced to the registry. Whether the internet can actually reach you is decided out there,"
	log "not in here: the registry replies from outside and will not list a server that never answers."
	log "Watch for it:  docker logs -f fua-${INSTANCE}"
fi
